# Generated by Django 2.1.2 on 2018-10-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['album', 'track_number']},
        ),
    ]
