# Generated by Django 2.1.2 on 2018-10-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0003_auto_20181014_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='slug',
            field=models.SlugField(default='unknown'),
            preserve_default=False,
        ),
    ]
