# Generated by Django 2.1.2 on 2018-10-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0005_auto_20181015_0627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solo',
            options={'ordering': ['track', 'start_time']},
        ),
    ]
